brands = {'Abarth': '/Abarth-2-marka', 'Acura': '/Acura-3-marka', 'Aero': '/Aero-4-marka', 
'Alfa Romeo': '/Alfa-Romeo-5-marka', 'Alpine': '/Alpine-6-marka', 'ARO': '/ARO-1-marka', 
'Arrinera': '/Arrinera-7-marka', 'Ascari': '/Ascari-8-marka', 'Aston Martin': '/Aston-Martin-9-marka', 
'Audi': '/Audi-10-marka', 'Austin': '/Austin-11-marka', 'Autobianchi': '/Autobianchi-12-marka', 
'Avia': '/Avia-13-marka', 'Bentley': '/Bentley-15-marka', 'BMW': '/BMW-14-marka',
'British Leyland': '/British-Leyland-16-marka', 'Bugatti': '/Bugatti-17-marka', 
'Buick': '/Buick-18-marka', 'Cadillac': '/Cadillac-19-marka', 'Caterham': '/Caterham-20-marka', 
'Chevrolet': '/Chevrolet-21-marka', 'Chrysler': '/Chrysler-22-marka', 'Citroen': '/Citroen-23-marka', 
'Cizeta': '/Cizeta-24-marka', 'Dacia': '/Dacia-27-marka', 'Daewoo': '/Daewoo-28-marka', 
'DAF': '/DAF-25-marka', 'Daihatsu': '/Daihatsu-29-marka', 'Daimler': '/Daimler-30-marka',
'Datsun': '/Datsun-31-marka', 'De Tomaso': '/De-Tomaso-32-marka', 'DeLorean': '/DeLorean-33-marka', 
'DKW': '/DKW-26-marka', 'Dodge': '/Dodge-34-marka', 'Eagle': '/Eagle-35-marka', 
'Falcon': '/Falcon-39-marka', 'Ferrari': '/Ferrari-40-marka', 'Fiat': '/Fiat-41-marka',
'Fisker': '/Fisker-42-marka', 'Ford': '/Ford-43-marka', 'FSC Star': '/FSC-Star-36-marka', 
'FSM': '/FSM-37-marka', 'FSO': '/FSO-38-marka', 'GAZ': '/GAZ-44-marka', 'GMC': '/GMC-45-marka', 
'Gumpert': '/Gumpert-46-marka', 'Holden': '/Holden-47-marka', 'Honda': '/Honda-48-marka', 
'Horch': '/Horch-49-marka', 'Hummer': '/Hummer-50-marka', 'Hyundai': '/Hyundai-51-marka', 
'Infiniti': '/Infiniti-52-marka', 'Isuzu': '/Isuzu-53-marka', 'Jaguar': '/Jaguar-54-marka', 
'Jeep': '/Jeep-55-marka', 'Jelczańskie Zakłady Samochodowe': '/Jelczanskie-Zaklady-Samochodowe-56-marka',
'Jensen': '/Jensen-57-marka', 'Kia': '/Kia-59-marka', 'Koenigsegg': '/Koenigsegg-60-marka', 
'KTM': '/KTM-58-marka', 'Lada': '/Lada-61-marka', 'Lamborghini': '/Lamborghini-62-marka', 
'Lanchester': '/Lanchester-63-marka', 'Lancia': '/Lancia-64-marka', 'Land Rover': '/Land-Rover-65-marka', 
'Lexus': '/Lexus-66-marka', 'Lincoln': '/Lincoln-67-marka', 'Lotus': '/Lotus-68-marka', 
'Magna Steyr': '/Magna-Steyr-71-marka', 'Mahindra': '/Mahindra-72-marka', 'MAN': '/MAN-69-marka',
'Mansory': '/Mansory-73-marka', 'Marussia': '/Marussia-74-marka', 'Maruti Suzuki': '/Maruti-Suzuki-75-marka', 
'Maserati': '/Maserati-76-marka', 'Matra': '/Matra-77-marka', 'Maybach': '/Maybach-78-marka', 
'Mazda': '/Mazda-79-marka', 'McLaren': '/McLaren-80-marka', 'Mercedes-Benz': '/Mercedes-Benz-81-marka', 
'Mercury': '/Mercury-82-marka', 'MG': '/MG-70-marka', 'Mini': '/Mini-83-marka', 'Mitsubishi': '/Mitsubishi-84-marka', 
'Morgan': '/Morgan-85-marka', 'Morris': '/Morris-86-marka', 'Moskwicz': '/Moskwicz-87-marka', 'Neoplan': '/Neoplan-89-marka',
'Nissan': '/Nissan-90-marka', 'Noble': '/Noble-91-marka', 'NSU': '/NSU-88-marka', 'Oldsmobile': '/Oldsmobile-92-marka', 
'Oltcit': '/Oltcit-93-marka', 'Opel': '/Opel-94-marka', 'Otokar': '/Otokar-95-marka', 'Otosan': '/Otosan-96-marka', 
'Packard': '/Packard-97-marka', 'Pagani': '/Pagani-98-marka', 'Peugeot': '/Peugeot-99-marka', 'Plymouth': '/Plymouth-100-marka',
'Polonez': '/Polonez-154-marka', 'Pontiac': '/Pontiac-101-marka', 'Porsche': '/Porsche-102-marka', 'Proton': '/Proton-103-marka', 
'Puch': '/Puch-104-marka', 
'Ram': '/Ram-105-marka', 'Rambler': '/Rambler-106-marka', 'Renault': '/Renault-107-marka', 
'Robur': '/Robur-108-marka', 'Rolls Royce': '/Rolls-Royce-109-marka', 'Rover': '/Rover-110-marka', 
'Saab': '/Saab-112-marka', 'Saleen': '/Saleen-113-marka', 'Saturn': '/Saturn-114-marka',
'Scania': '/Scania-115-marka', 'Scion': '/Scion-116-marka', 'SEAT': '/SEAT-111-marka', 
'Simson': '/Simson-117-marka', 'Skoda': '/Skoda-118-marka', 'Solaris': '/Solaris-119-marka', 
'Spyker': '/Spyker-120-marka', 'SsangYong': '/SsangYong-121-marka', 
'Steyr-Daimler-Puch': '/Steyr-Daimler-Puch-122-marka', 'Studebaker': '/Studebaker-123-marka',
'Subaru': '/Subaru-124-marka', 'Suzuki': '/Suzuki-125-marka', 'Talbot': '/Talbot-127-marka', 
'Tata': '/Tata-128-marka', 'Tatra': '/Tatra-129-marka', 'Tesla': '/Tesla-130-marka', 
'Toyota': '/Toyota-131-marka', 'Trabant': '/Trabant-132-marka', 'TVR': '/TVR-126-marka',
'UAZ': '/UAZ-133-marka', 'Vauxhall': '/Vauxhall-134-marka', 'Venturi': 
'/Venturi-135-marka', 'Volkswagen': '/Volkswagen-136-marka', 'Volvo': '/Volvo-137-marka', 'Wanderer': '/Wanderer-139-marka', 'Wartburg': 
'/Wartburg-140-marka', 'WAZ': '/WAZ-138-marka', 'Wiesmann': '/Wiesmann-141-marka', 'Willys': '/Willys-142-marka',
'Yamaha': '/Yamaha-143-marka', 'Zastava': '/Zastava-146-marka', 'ZAZ': '/ZAZ-144-marka', 'Zil': '/Zil-147-marka', 'ZSD Nysa': '/ZSD-Nysa-145-marka'}